#!/bin/bash
# Regenerate assets_data.h — bakes assets/ into the program so the built
# binary is fully self-contained (no files to install alongside it).
set -euo pipefail
cd "$(dirname "$0")"

out=assets_data.h
emit() { # emit <symbol> <file>
  local sym=$1 file=$2
  echo "static const unsigned char ${sym}[] = {"
  xxd -i < "$file" | sed 's/^/  /'
  echo "};"
  echo "static const unsigned long ${sym}Len = sizeof(${sym});"
  echo
}

{
  echo "// Generated by embed_assets.sh — do not edit."
  echo "// Source: assets/the-rock.gif, assets/explosion-meme.mp3"
  echo "#pragma once"
  echo
  emit kRockGif        assets/the-rock.gif
  emit kExplosionMp3   assets/explosion-meme.mp3
} > "$out"

echo "wrote $out ($(wc -c < "$out" | tr -d ' ') bytes)"
