// therockware (macOS)
//
// Background agent: every mouse click pops the-rock.gif at the pointer and
// fires explosion-meme.mp3.
//
// Everything here is system frameworks only -- the GIF is decoded frame by
// frame with ImageIO and driven by a CALayer keyframe animation, so there is
// no GIF-player dependency of any kind. The gif and the mp3 are compiled into
// the binary (assets_data.h), so the installed program is a single file with
// nothing to load off disk.
//
// Build: ./build.sh   (clang++ -x objective-c++, see that script)

#import <Cocoa/Cocoa.h>
#import <AVFoundation/AVFoundation.h>
#import <ApplicationServices/ApplicationServices.h>
#import <ImageIO/ImageIO.h>

#include "../assets_data.h" // kRockGif / kExplosionMp3, generated by embed_assets.sh

// ---------------------------------------------------------------- tunables

static const NSInteger kPoolSize = 6;        // concurrent pops / sounds
static const CGFloat kMaxEdge = 260.0;       // longest gif edge, points
static const NSTimeInterval kMinShow = 0.35; // floor on visible time
static const NSTimeInterval kMaxShow = 4.00; // ceiling on visible time
static const NSTimeInterval kPopIn = 0.11;   // scale-in duration
static const NSTimeInterval kFadeOut = 0.16; // fade-out duration

// -------------------------------------------------------------- gif decode

@interface RockGif : NSObject
@property(nonatomic, strong) NSArray *frames;   // CGImageRef boxed as id
@property(nonatomic, strong) NSArray *keyTimes; // count == frames+1
@property(nonatomic, assign) NSTimeInterval duration;
@property(nonatomic, assign) NSSize size;
@end

@implementation RockGif

+ (instancetype)gifWithData:(NSData *)data
{
    if (!data.length)
        return nil;

    CGImageSourceRef src = CGImageSourceCreateWithData((__bridge CFDataRef)data, NULL);
    if (!src)
        return nil;

    size_t count = CGImageSourceGetCount(src);
    if (count == 0)
    {
        CFRelease(src);
        return nil;
    }

    NSMutableArray *frames = [NSMutableArray arrayWithCapacity:count];
    NSMutableArray *delays = [NSMutableArray arrayWithCapacity:count];
    NSTimeInterval total = 0.0;

    for (size_t i = 0; i < count; i++)
    {
        CGImageRef img = CGImageSourceCreateImageAtIndex(src, i, NULL);
        if (!img)
            continue;
        [frames addObject:(__bridge_transfer id)img];

        // Per-frame delay, with the same clamping every browser applies to
        // pathological 0ms / 10ms gifs.
        NSTimeInterval delay = 0.1;
        CFDictionaryRef props = CGImageSourceCopyPropertiesAtIndex(src, i, NULL);
        if (props)
        {
            CFDictionaryRef gif =
                (CFDictionaryRef)CFDictionaryGetValue(props, kCGImagePropertyGIFDictionary);
            if (gif)
            {
                CFNumberRef n =
                    (CFNumberRef)CFDictionaryGetValue(gif, kCGImagePropertyGIFUnclampedDelayTime);
                if (!n)
                    n = (CFNumberRef)CFDictionaryGetValue(gif, kCGImagePropertyGIFDelayTime);
                double v = 0.0;
                if (n && CFNumberGetValue(n, kCFNumberDoubleType, &v) && v > 0.0)
                    delay = v;
            }
            CFRelease(props);
        }
        if (delay < 0.011)
            delay = 0.1;

        [delays addObject:@(delay)];
        total += delay;
    }

    if (frames.count == 0 || total <= 0.0)
    {
        CFRelease(src);
        return nil;
    }

    // Discrete keyframe animations want one more key time than value.
    NSMutableArray *keyTimes = [NSMutableArray arrayWithCapacity:frames.count + 1];
    NSTimeInterval acc = 0.0;
    for (NSNumber *d in delays)
    {
        [keyTimes addObject:@(acc / total)];
        acc += d.doubleValue;
    }
    [keyTimes addObject:@(1.0)];

    CGImageRef first = (__bridge CGImageRef)frames[0];
    CGFloat w = (CGFloat)CGImageGetWidth(first);
    CGFloat h = (CGFloat)CGImageGetHeight(first);
    CGFloat scale = 1.0;
    if (w > kMaxEdge || h > kMaxEdge)
        scale = kMaxEdge / MAX(w, h);

    CFRelease(src);

    RockGif *g = [[RockGif alloc] init];
    g.frames = frames;
    g.keyTimes = keyTimes;
    g.duration = total;
    g.size = NSMakeSize(round(w * scale), round(h * scale));
    return g;
}

@end

// ------------------------------------------------------------ overlay pop

// A click-through, always-on-top, transparent window that renders one run of
// the gif centred on a point and then hides itself.
@interface RockPop : NSObject
@property(nonatomic, strong) NSWindow *window;
@property(nonatomic, strong) CALayer *layer;
@property(nonatomic, strong) RockGif *gif;
@property(nonatomic, strong) NSTimer *hideTimer;
@property(nonatomic, assign) BOOL busy;
@end

@implementation RockPop

- (instancetype)initWithGif:(RockGif *)gif
{
    self = [super init];
    if (!self)
        return nil;

    _gif = gif;

    NSRect frame = NSMakeRect(0, 0, gif.size.width, gif.size.height);
    _window = [[NSWindow alloc] initWithContentRect:frame
                                          styleMask:NSWindowStyleMaskBorderless
                                            backing:NSBackingStoreBuffered
                                              defer:NO];
    _window.opaque = NO;
    _window.backgroundColor = [NSColor clearColor];
    _window.hasShadow = NO;
    _window.ignoresMouseEvents = YES; // never eat a real click
    _window.level = NSScreenSaverWindowLevel;
    _window.collectionBehavior = NSWindowCollectionBehaviorCanJoinAllSpaces |
                                 NSWindowCollectionBehaviorStationary |
                                 NSWindowCollectionBehaviorFullScreenAuxiliary |
                                 NSWindowCollectionBehaviorIgnoresCycle;
    _window.releasedWhenClosed = NO;
    if (@available(macOS 10.11, *))
        _window.animationBehavior = NSWindowAnimationBehaviorNone;

    NSView *content = _window.contentView;
    content.wantsLayer = YES;
    content.layer.backgroundColor = NSColor.clearColor.CGColor;

    _layer = [CALayer layer];
    _layer.frame = content.bounds;
    _layer.contentsGravity = kCAGravityResizeAspect;
    _layer.contents = gif.frames.firstObject;
    [content.layer addSublayer:_layer];

    return self;
}

- (void)popAt:(NSPoint)point forDuration:(NSTimeInterval)duration
{
    [self.hideTimer invalidate];
    self.busy = YES;

    NSSize s = self.gif.size;
    NSRect frame = NSMakeRect(round(point.x - s.width / 2.0),
                              round(point.y - s.height / 2.0),
                              s.width, s.height);
    [self.window setFrame:frame display:NO];

    [CATransaction begin];
    [CATransaction setDisableActions:YES];
    self.layer.frame = self.window.contentView.bounds;
    self.layer.opacity = 1.0;
    [self.layer removeAllAnimations];

    CAKeyframeAnimation *flip = [CAKeyframeAnimation animationWithKeyPath:@"contents"];
    flip.values = self.gif.frames;
    flip.keyTimes = self.gif.keyTimes;
    flip.calculationMode = kCAAnimationDiscrete;
    flip.duration = self.gif.duration;
    flip.repeatCount = HUGE_VALF;
    [self.layer addAnimation:flip forKey:@"rock"];

    CABasicAnimation *pop = [CABasicAnimation animationWithKeyPath:@"transform.scale"];
    pop.fromValue = @(0.55);
    pop.toValue = @(1.0);
    pop.duration = kPopIn;
    pop.timingFunction = [CAMediaTimingFunction functionWithControlPoints:0.2f:1.5f:0.4f:1.0f];
    [self.layer addAnimation:pop forKey:@"pop"];
    [CATransaction commit];

    [self.window orderFrontRegardless];

    self.hideTimer = [NSTimer scheduledTimerWithTimeInterval:MAX(duration - kFadeOut, 0.05)
                                                     repeats:NO
                                                       block:^(NSTimer *t) {
                                                         [self fadeOut];
                                                       }];
}

- (void)fadeOut
{
    [CATransaction begin];
    [CATransaction setCompletionBlock:^{
      [self hideNow];
    }];
    CABasicAnimation *fade = [CABasicAnimation animationWithKeyPath:@"opacity"];
    fade.fromValue = @(1.0);
    fade.toValue = @(0.0);
    fade.duration = kFadeOut;
    self.layer.opacity = 0.0;
    [self.layer addAnimation:fade forKey:@"fade"];
    [CATransaction commit];
}

- (void)hideNow
{
    [self.hideTimer invalidate];
    self.hideTimer = nil;
    [self.window orderOut:nil];
    [self.layer removeAllAnimations];
    self.busy = NO;
}

@end

// ------------------------------------------------------------- controller

@interface RockController : NSObject <AVAudioPlayerDelegate>
@property(nonatomic, strong) NSMutableArray<RockPop *> *pops;
@property(nonatomic, strong) NSMutableArray<AVAudioPlayer *> *players;
@property(nonatomic, assign) NSInteger popCursor;
@property(nonatomic, assign) NSInteger playerCursor;
@property(nonatomic, assign) NSTimeInterval showDuration;
@property(nonatomic, assign) BOOL enabled;
@property(nonatomic, strong) NSStatusItem *statusItem;
@property(nonatomic, strong) NSMenuItem *toggleItem;
@property(nonatomic, assign) CFMachPortRef tap;
@property(nonatomic, strong) NSTimer *permissionTimer;
@end

static RockController *gController = nil;

@implementation RockController

- (BOOL)loadAssets
{
    NSData *gifData = [NSData dataWithBytesNoCopy:(void *)kRockGif
                                           length:kRockGifLen
                                     freeWhenDone:NO];
    NSData *audio = [NSData dataWithBytesNoCopy:(void *)kExplosionMp3
                                         length:kExplosionMp3Len
                                   freeWhenDone:NO];

    RockGif *gif = [RockGif gifWithData:gifData];
    if (!gif)
    {
        NSLog(@"[therockware] embedded gif failed to decode");
        return NO;
    }

    self.players = [NSMutableArray array];
    NSTimeInterval audioLen = 0.0;
    for (NSInteger i = 0; i < kPoolSize; i++)
    {
        NSError *err = nil;
        AVAudioPlayer *p = [[AVAudioPlayer alloc] initWithData:audio error:&err];
        if (!p)
        {
            NSLog(@"[therockware] audio: %@", err);
            break;
        }
        [p prepareToPlay];
        audioLen = p.duration;
        [self.players addObject:p];
    }

    // Stay on screen as long as the meme is audible, within sane bounds.
    NSTimeInterval want = MAX(audioLen, gif.duration);
    self.showDuration = MIN(MAX(want, kMinShow), kMaxShow);

    self.pops = [NSMutableArray array];
    for (NSInteger i = 0; i < kPoolSize; i++)
    {
        [self.pops addObject:[[RockPop alloc] initWithGif:gif]];
    }
    return YES;
}

- (void)fireAt:(NSPoint)point
{
    if (!self.enabled)
        return;

    // Prefer an idle window; otherwise recycle round-robin so a machine-gun
    // clicker still gets a pop on every click.
    RockPop *pop = nil;
    for (RockPop *p in self.pops)
    {
        if (!p.busy)
        {
            pop = p;
            break;
        }
    }
    if (!pop)
    {
        pop = self.pops[self.popCursor % self.pops.count];
        self.popCursor++;
    }
    [pop popAt:point forDuration:self.showDuration];

    AVAudioPlayer *player = nil;
    for (AVAudioPlayer *p in self.players)
    {
        if (!p.isPlaying)
        {
            player = p;
            break;
        }
    }
    if (!player && self.players.count)
    {
        player = self.players[self.playerCursor % self.players.count];
        self.playerCursor++;
        [player stop];
    }
    player.currentTime = 0.0;
    [player play];
}

// ----------------------------------------------------------- event tap

static CGEventRef TapCallback(CGEventTapProxy proxy, CGEventType type,
                              CGEventRef event, void *refcon)
{
    RockController *self_ = (__bridge RockController *)refcon;

    if (type == kCGEventTapDisabledByTimeout || type == kCGEventTapDisabledByUserInput)
    {
        if (self_.tap)
            CGEventTapEnable(self_.tap, true);
        return event;
    }

    // NSEvent.mouseLocation is already in global bottom-left screen space,
    // which is exactly what NSWindow wants.
    NSPoint where = [NSEvent mouseLocation];
    [self_ fireAt:where];
    return event; // listen-only tap: the click passes through untouched
}

- (BOOL)startTap
{
    CGEventMask mask = CGEventMaskBit(kCGEventLeftMouseDown) |
                       CGEventMaskBit(kCGEventRightMouseDown) |
                       CGEventMaskBit(kCGEventOtherMouseDown);

    CFMachPortRef tap = CGEventTapCreate(kCGSessionEventTap,
                                         kCGHeadInsertEventTap,
                                         kCGEventTapOptionListenOnly,
                                         mask,
                                         TapCallback,
                                         (__bridge void *)self);
    if (!tap)
        return NO;

    CFRunLoopSourceRef source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0);
    CFRunLoopAddSource(CFRunLoopGetMain(), source, kCFRunLoopCommonModes);
    CFRelease(source);
    CGEventTapEnable(tap, true);
    self.tap = tap;
    return YES;
}

- (void)waitForPermission
{
    // Accessibility can be granted after launch; poll until the tap takes.
    self.permissionTimer =
        [NSTimer scheduledTimerWithTimeInterval:2.0
                                        repeats:YES
                                          block:^(NSTimer *t) {
                                            if (AXIsProcessTrusted() && [self startTap])
                                            {
                                                [t invalidate];
                                                self.permissionTimer = nil;
                                                [self refreshStatusTitle];
                                                NSLog(@"[therockware] accessibility granted, tap live");
                                            }
                                          }];
}

// -------------------------------------------------------------- menu bar

- (void)buildStatusItem
{
    self.statusItem = [[NSStatusBar systemStatusBar]
        statusItemWithLength:NSVariableStatusItemLength];
    self.statusItem.button.title = @"🪨";

    NSMenu *menu = [[NSMenu alloc] init];
    self.toggleItem = [[NSMenuItem alloc] initWithTitle:@"Pause"
                                                 action:@selector(toggleEnabled:)
                                          keyEquivalent:@""];
    self.toggleItem.target = self;
    [menu addItem:self.toggleItem];

    NSMenuItem *test = [[NSMenuItem alloc] initWithTitle:@"Test Pop"
                                                  action:@selector(testPop:)
                                           keyEquivalent:@""];
    test.target = self;
    [menu addItem:test];

    [menu addItem:[NSMenuItem separatorItem]];

    NSMenuItem *quit = [[NSMenuItem alloc] initWithTitle:@"Quit TheRockWare"
                                                  action:@selector(quit:)
                                           keyEquivalent:@"q"];
    quit.target = self;
    [menu addItem:quit];

    self.statusItem.menu = menu;
    [self refreshStatusTitle];
}

- (void)refreshStatusTitle
{
    BOOL live = (self.tap != NULL);
    if (!live)
    {
        self.statusItem.button.title = @"🪨⚠️";
        self.toggleItem.title = @"Waiting for Accessibility…";
    }
    else
    {
        self.statusItem.button.title = self.enabled ? @"🪨" : @"🪨💤";
        self.toggleItem.title = self.enabled ? @"Pause" : @"Resume";
    }
}

- (void)toggleEnabled:(id)sender
{
    self.enabled = !self.enabled;
    if (!self.enabled)
    {
        for (RockPop *p in self.pops)
            [p hideNow];
        for (AVAudioPlayer *p in self.players)
            [p stop];
    }
    [self refreshStatusTitle];
}

- (void)testPop:(id)sender
{
    BOOL wasEnabled = self.enabled;
    self.enabled = YES;
    [self fireAt:[NSEvent mouseLocation]];
    self.enabled = wasEnabled;
}

- (void)quit:(id)sender
{
    [NSApp terminate:nil];
}

@end

// -------------------------------------------------------------- app entry

@interface RockAppDelegate : NSObject <NSApplicationDelegate>
@end

@implementation RockAppDelegate

- (void)applicationDidFinishLaunching:(NSNotification *)note
{
    gController = [[RockController alloc] init];
    gController.enabled = YES;

    if (![gController loadAssets])
    {
        NSLog(@"[therockware] failed to initialise embedded media");
        [NSApp terminate:nil];
        return;
    }

    [gController buildStatusItem];

    // Global click monitoring needs Accessibility. Ask once, then wait.
    NSDictionary *opts = @{(__bridge id)kAXTrustedCheckOptionPrompt : @YES};
    BOOL trusted = AXIsProcessTrustedWithOptions((__bridge CFDictionaryRef)opts);

    if (!trusted || ![gController startTap])
    {
        NSLog(@"[therockware] waiting for Accessibility permission…");
        [gController waitForPermission];
    }
    [gController refreshStatusTitle];
}

@end

int main(int argc, const char *argv[])
{
    @autoreleasepool
    {
        NSApplication *app = [NSApplication sharedApplication];
        // Accessory: no Dock icon, no menu bar takeover -- it just lives up
        // in the status bar.
        [app setActivationPolicy:NSApplicationActivationPolicyAccessory];
        RockAppDelegate *delegate = [[RockAppDelegate alloc] init];
        app.delegate = delegate;
        [app run];
    }
    return 0;
}
