// therockware (Windows)
//
// Background agent: every mouse click pops the-rock.gif at the pointer and
// fires explosion-meme.mp3.
//
// Mirror of mac.cpp. System APIs only -- the GIF is decoded and composited
// frame by frame with WIC, the MP3 is decoded to PCM in memory with Media
// Foundation and played through XAudio2. Both are compiled into the binary
// (assets_data.h), so the installed program is one .exe that loads nothing
// off disk.
//
// Build: build.bat   (MSVC, /SUBSYSTEM:WINDOWS -- no console window)
// Sign:  sign.ps1
//
//   therockware.exe              run now
//   therockware.exe --install    copy to %LOCALAPPDATA% + start at login
//   therockware.exe --uninstall  undo that

#ifndef UNICODE
#define UNICODE
#endif
#ifndef _UNICODE
#define _UNICODE
#endif
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX

#include <windows.h>
#include <shellapi.h>
#include <shlwapi.h>
#include <shlobj.h>
#include <wincodec.h>
#include <mfapi.h>
#include <mfidl.h>
#include <mfreadwrite.h>
#include <xaudio2.h>

#include <algorithm>
#include <string>
#include <vector>
#include <wchar.h>

#include "../assets_data.h"   // kRockGif / kExplosionMp3, generated by embed_assets.sh

// ---------------------------------------------------------------- tunables

static const int    kPoolSize   = 6;      // concurrent pops / sounds
static const double kMaxEdge    = 260.0;  // longest gif edge, at 100% DPI
static const UINT   kMinShowMs  = 350;    // floor on visible time
static const UINT   kMaxShowMs  = 4000;   // ceiling on visible time
static const UINT   kFadeMs     = 160;    // fade-out duration
static const UINT   kFadeStepMs = 16;     // ~60fps fade

static const wchar_t *kAppName   = L"TheRockWare";
static const wchar_t *kMainClass = L"RockWareMain";
static const wchar_t *kPopClass  = L"RockWarePop";
static const wchar_t *kMutexName = L"Local\\TheRockWareSingleton";
static const wchar_t *kRunKey    = L"Software\\Microsoft\\Windows\\CurrentVersion\\Run";
static const wchar_t *kRunValue  = L"TheRockWare";

#define WM_ROCK_TRAY (WM_APP + 1)
#define WM_ROCK_FIRE (WM_APP + 2)

#define ID_TIMER_FRAME 1
#define ID_TIMER_LIFE  2
#define ID_TIMER_FADE  3

#define IDM_TOGGLE 100
#define IDM_TEST   101
#define IDM_STARTUP 102
#define IDM_QUIT   103

template <class T> static void SafeRelease(T **p) {
    if (*p) { (*p)->Release(); *p = nullptr; }
}

// --------------------------------------------------------------- gif decode

struct GifFrame {
    HBITMAP bmp   = nullptr;   // 32bpp top-down premultiplied BGRA DIB
    UINT    delay = 100;       // milliseconds
};

struct RockGif {
    std::vector<GifFrame> frames;
    UINT width   = 0;          // display size, DPI-scaled
    UINT height  = 0;
    UINT totalMs = 0;
};

static HBITMAP MakeDib(UINT w, UINT h, void **bitsOut) {
    BITMAPINFO bi = {};
    bi.bmiHeader.biSize        = sizeof(BITMAPINFOHEADER);
    bi.bmiHeader.biWidth       = (LONG)w;
    bi.bmiHeader.biHeight      = -(LONG)h;   // top-down
    bi.bmiHeader.biPlanes      = 1;
    bi.bmiHeader.biBitCount    = 32;
    bi.bmiHeader.biCompression = BI_RGB;
    return CreateDIBSection(nullptr, &bi, DIB_RGB_COLORS, bitsOut, nullptr, 0);
}

static UINT ReadMetaUInt(IWICMetadataQueryReader *r, const wchar_t *name, UINT fallback) {
    if (!r) return fallback;
    PROPVARIANT v;
    PropVariantInit(&v);
    UINT out = fallback;
    if (SUCCEEDED(r->GetMetadataByName(name, &v))) {
        switch (v.vt) {
            case VT_UI1: out = v.bVal;  break;
            case VT_UI2: out = v.uiVal; break;
            case VT_UI4: out = v.ulVal; break;
            default: break;
        }
    }
    PropVariantClear(&v);
    return out;
}

// Source-over of a premultiplied BGRA rect onto the premultiplied canvas.
static void BlendOnto(BYTE *canvas, UINT cw, UINT ch,
                      const BYTE *src, UINT sw, UINT sh, UINT left, UINT top) {
    for (UINT y = 0; y < sh; y++) {
        UINT dy = top + y;
        if (dy >= ch) break;
        const BYTE *s = src + (size_t)y * sw * 4;
        BYTE *d = canvas + ((size_t)dy * cw + left) * 4;
        for (UINT x = 0; x < sw; x++, s += 4, d += 4) {
            if (left + x >= cw) break;
            BYTE sa = s[3];
            if (sa == 255) {
                memcpy(d, s, 4);
            } else if (sa) {
                UINT inv = 255 - sa;
                d[0] = (BYTE)(s[0] + ((d[0] * inv + 127) / 255));
                d[1] = (BYTE)(s[1] + ((d[1] * inv + 127) / 255));
                d[2] = (BYTE)(s[2] + ((d[2] * inv + 127) / 255));
                d[3] = (BYTE)(s[3] + ((d[3] * inv + 127) / 255));
            }
        }
    }
}

// Decodes the embedded GIF into a flat list of fully composited frames.
// WIC hands back raw sub-rectangles, so disposal methods are applied here --
// otherwise partial-update gifs smear.
static bool DecodeGif(RockGif &out, UINT dpi) {
    IWICImagingFactory *factory = nullptr;
    IWICBitmapDecoder  *decoder = nullptr;
    IStream            *stream  = nullptr;
    bool ok = false;

    if (FAILED(CoCreateInstance(CLSID_WICImagingFactory, nullptr, CLSCTX_INPROC_SERVER,
                                IID_PPV_ARGS(&factory))))
        return false;

    stream = SHCreateMemStream(kRockGif, (UINT)kRockGifLen);
    if (!stream) { SafeRelease(&factory); return false; }

    if (FAILED(factory->CreateDecoderFromStream(stream, nullptr,
                                                WICDecodeMetadataCacheOnLoad, &decoder)))
        goto done;

    {
        UINT count = 0;
        if (FAILED(decoder->GetFrameCount(&count)) || count == 0) goto done;

        UINT canvasW = 0, canvasH = 0;
        IWICMetadataQueryReader *global = nullptr;
        if (SUCCEEDED(decoder->GetMetadataQueryReader(&global))) {
            canvasW = ReadMetaUInt(global, L"/logscrdesc/Width", 0);
            canvasH = ReadMetaUInt(global, L"/logscrdesc/Height", 0);
            SafeRelease(&global);
        }
        if (!canvasW || !canvasH) {
            IWICBitmapFrameDecode *f0 = nullptr;
            if (FAILED(decoder->GetFrame(0, &f0))) goto done;
            f0->GetSize(&canvasW, &canvasH);
            SafeRelease(&f0);
        }
        if (!canvasW || !canvasH) goto done;

        // Display size: cap the long edge, then scale for this monitor's DPI
        // so it isn't a postage stamp on a 4K panel.
        double scale = 1.0;
        double longEdge = (double)(canvasW > canvasH ? canvasW : canvasH);
        if (longEdge > kMaxEdge) scale = kMaxEdge / longEdge;
        scale *= (double)dpi / 96.0;
        UINT dispW = (UINT)(canvasW * scale + 0.5);
        UINT dispH = (UINT)(canvasH * scale + 0.5);
        if (dispW < 1) dispW = 1;
        if (dispH < 1) dispH = 1;

        std::vector<BYTE> canvas((size_t)canvasW * canvasH * 4, 0);
        std::vector<BYTE> saved;                       // for disposal method 3
        UINT prevDisposal = 0, prevL = 0, prevT = 0, prevW = 0, prevH = 0;

        for (UINT i = 0; i < count; i++) {
            IWICBitmapFrameDecode   *frame = nullptr;
            IWICFormatConverter     *conv  = nullptr;
            IWICMetadataQueryReader *meta  = nullptr;

            if (FAILED(decoder->GetFrame(i, &frame))) continue;

            UINT fw = 0, fh = 0, left = 0, top = 0, delay = 10, disposal = 0;
            frame->GetSize(&fw, &fh);
            if (SUCCEEDED(frame->GetMetadataQueryReader(&meta))) {
                left     = ReadMetaUInt(meta, L"/imgdesc/Left", 0);
                top      = ReadMetaUInt(meta, L"/imgdesc/Top", 0);
                delay    = ReadMetaUInt(meta, L"/grctlext/Delay", 10);
                disposal = ReadMetaUInt(meta, L"/grctlext/Disposal", 0);
                SafeRelease(&meta);
            }

            // Undo the previous frame the way the spec says to, before drawing.
            if (prevDisposal == 2 && prevW && prevH && prevL < canvasW) {
                UINT runW = (prevL + prevW > canvasW) ? (canvasW - prevL) : prevW;
                for (UINT y = 0; y < prevH; y++) {
                    UINT dy = prevT + y;
                    if (dy >= canvasH) break;
                    memset(&canvas[((size_t)dy * canvasW + prevL) * 4], 0, (size_t)runW * 4);
                }
            } else if (prevDisposal == 3 && saved.size() == canvas.size()) {
                canvas = saved;
            }
            if (disposal == 3) saved = canvas;

            if (SUCCEEDED(factory->CreateFormatConverter(&conv)) &&
                SUCCEEDED(conv->Initialize(frame, GUID_WICPixelFormat32bppPBGRA,
                                           WICBitmapDitherTypeNone, nullptr, 0.0,
                                           WICBitmapPaletteTypeCustom))) {
                std::vector<BYTE> px((size_t)fw * fh * 4);
                if (SUCCEEDED(conv->CopyPixels(nullptr, fw * 4, (UINT)px.size(), px.data())))
                    BlendOnto(canvas.data(), canvasW, canvasH, px.data(), fw, fh, left, top);
            }
            SafeRelease(&conv);
            SafeRelease(&frame);

            // Snapshot the composited canvas into a ready-to-blit DIB.
            void *bits = nullptr;
            HBITMAP bmp = MakeDib(dispW, dispH, &bits);
            if (bmp && bits) {
                bool copied = false;
                if (dispW == canvasW && dispH == canvasH) {
                    memcpy(bits, canvas.data(), canvas.size());
                    copied = true;
                } else {
                    IWICBitmap       *src    = nullptr;
                    IWICBitmapScaler *scaler = nullptr;
                    if (SUCCEEDED(factory->CreateBitmapFromMemory(
                            canvasW, canvasH, GUID_WICPixelFormat32bppPBGRA,
                            canvasW * 4, (UINT)canvas.size(), canvas.data(), &src)) &&
                        SUCCEEDED(factory->CreateBitmapScaler(&scaler)) &&
                        SUCCEEDED(scaler->Initialize(src, dispW, dispH,
                                                     WICBitmapInterpolationModeFant))) {
                        copied = SUCCEEDED(scaler->CopyPixels(
                            nullptr, dispW * 4, dispW * dispH * 4, (BYTE *)bits));
                    }
                    SafeRelease(&scaler);
                    SafeRelease(&src);
                }
                if (copied) {
                    GifFrame gf;
                    gf.bmp   = bmp;
                    // GIF delays are hundredths; clamp the pathological ones
                    // the same way browsers do.
                    gf.delay = (delay < 2) ? 100 : delay * 10;
                    out.frames.push_back(gf);
                    out.totalMs += gf.delay;
                } else {
                    DeleteObject(bmp);
                }
            }

            prevDisposal = disposal;
            prevL = left; prevT = top; prevW = fw; prevH = fh;
        }

        out.width  = dispW;
        out.height = dispH;
        ok = !out.frames.empty();
    }

done:
    SafeRelease(&decoder);
    SafeRelease(&stream);
    SafeRelease(&factory);
    return ok;
}

// ------------------------------------------------------------------- audio

struct RockAudio {
    IXAudio2                          *engine = nullptr;
    IXAudio2MasteringVoice            *master = nullptr;
    std::vector<IXAudio2SourceVoice *> voices;
    std::vector<BYTE>                  pcm;
    int                                cursor = 0;
    UINT                               durationMs = 0;
};

static bool DecodeMp3(std::vector<BYTE> &pcm, WAVEFORMATEX **wfxOut) {
    IStream         *stream = nullptr;
    IMFByteStream   *bytes  = nullptr;
    IMFSourceReader *reader = nullptr;
    IMFMediaType    *want   = nullptr;
    IMFMediaType    *actual = nullptr;
    bool ok = false;

    stream = SHCreateMemStream(kExplosionMp3, (UINT)kExplosionMp3Len);
    if (!stream) return false;

    if (FAILED(MFCreateMFByteStreamOnStream(stream, &bytes))) goto done;
    if (FAILED(MFCreateSourceReaderFromByteStream(bytes, nullptr, &reader))) goto done;
    if (FAILED(MFCreateMediaType(&want))) goto done;

    want->SetGUID(MF_MT_MAJOR_TYPE, MFMediaType_Audio);
    want->SetGUID(MF_MT_SUBTYPE, MFAudioFormat_PCM);
    if (FAILED(reader->SetCurrentMediaType(MF_SOURCE_READER_FIRST_AUDIO_STREAM,
                                           nullptr, want))) goto done;
    if (FAILED(reader->GetCurrentMediaType(MF_SOURCE_READER_FIRST_AUDIO_STREAM,
                                           &actual))) goto done;

    {
        UINT32 wfxSize = 0;
        if (FAILED(MFCreateWaveFormatExFromMFMediaType(actual, wfxOut, &wfxSize))) goto done;

        for (;;) {
            DWORD      flags  = 0;
            IMFSample *sample = nullptr;
            if (FAILED(reader->ReadSample(MF_SOURCE_READER_FIRST_AUDIO_STREAM, 0,
                                          nullptr, &flags, nullptr, &sample)))
                break;
            if (flags & MF_SOURCE_READERF_ENDOFSTREAM) { SafeRelease(&sample); break; }
            if (!sample) continue;

            IMFMediaBuffer *buf = nullptr;
            if (SUCCEEDED(sample->ConvertToContiguousBuffer(&buf))) {
                BYTE *p = nullptr; DWORD len = 0;
                if (SUCCEEDED(buf->Lock(&p, nullptr, &len))) {
                    pcm.insert(pcm.end(), p, p + len);
                    buf->Unlock();
                }
                SafeRelease(&buf);
            }
            SafeRelease(&sample);
        }
        ok = !pcm.empty();
    }

done:
    SafeRelease(&actual);
    SafeRelease(&want);
    SafeRelease(&reader);
    SafeRelease(&bytes);
    SafeRelease(&stream);
    return ok;
}

static bool InitAudio(RockAudio &a) {
    WAVEFORMATEX *wfx = nullptr;
    if (!DecodeMp3(a.pcm, &wfx) || !wfx) return false;

    a.durationMs = wfx->nAvgBytesPerSec
                 ? (UINT)((a.pcm.size() * 1000ULL) / wfx->nAvgBytesPerSec) : 0;

    bool ok = false;
    if (SUCCEEDED(XAudio2Create(&a.engine, 0, XAUDIO2_DEFAULT_PROCESSOR)) &&
        SUCCEEDED(a.engine->CreateMasteringVoice(&a.master))) {
        for (int i = 0; i < kPoolSize; i++) {
            IXAudio2SourceVoice *v = nullptr;
            if (FAILED(a.engine->CreateSourceVoice(&v, wfx))) break;
            a.voices.push_back(v);
        }
        ok = !a.voices.empty();
    }
    CoTaskMemFree(wfx);
    return ok;
}

static void PlayBang(RockAudio &a) {
    if (a.voices.empty()) return;

    IXAudio2SourceVoice *voice = nullptr;
    for (size_t i = 0; i < a.voices.size(); i++) {
        XAUDIO2_VOICE_STATE st = {};
        a.voices[i]->GetState(&st);
        if (st.BuffersQueued == 0) { voice = a.voices[i]; break; }
    }
    if (!voice) {                       // all busy: steal one, round-robin
        voice = a.voices[a.cursor % (int)a.voices.size()];
        a.cursor++;
        voice->Stop(0);
        voice->FlushSourceBuffers();
    }

    XAUDIO2_BUFFER buf = {};
    buf.Flags      = XAUDIO2_END_OF_STREAM;
    buf.AudioBytes = (UINT32)a.pcm.size();
    buf.pAudioData = a.pcm.data();
    if (SUCCEEDED(voice->SubmitSourceBuffer(&buf))) voice->Start(0);
}

// -------------------------------------------------------------- overlay pop

// A click-through, always-on-top, per-pixel-alpha window that plays one run of
// the gif centred on a point and then fades itself out.
struct Pop {
    HWND hwnd    = nullptr;
    UINT frame   = 0;
    UINT elapsed = 0;
    BYTE alpha   = 255;
    bool busy    = false;
    int  x = 0, y = 0;
};

struct AppState {
    HINSTANCE inst    = nullptr;
    HWND      main    = nullptr;
    HHOOK     hook    = nullptr;
    bool      enabled = true;
    UINT      showMs  = 1500;
    RockGif   gif;
    RockAudio audio;
    std::vector<Pop *> pops;
    int       popCursor = 0;
    NOTIFYICONDATAW nid = {};
};

static AppState g;

static void PaintPop(Pop *p, BYTE alpha) {
    if (p->frame >= g.gif.frames.size()) return;

    HDC screen = GetDC(nullptr);
    HDC mem    = CreateCompatibleDC(screen);
    HGDIOBJ old = SelectObject(mem, g.gif.frames[p->frame].bmp);

    POINT src = {0, 0};
    POINT dst = {p->x, p->y};
    SIZE  sz  = {(LONG)g.gif.width, (LONG)g.gif.height};
    BLENDFUNCTION bf = {};
    bf.BlendOp             = AC_SRC_OVER;
    bf.SourceConstantAlpha = alpha;
    bf.AlphaFormat         = AC_SRC_ALPHA;

    UpdateLayeredWindow(p->hwnd, screen, &dst, &sz, mem, &src, 0, &bf, ULW_ALPHA);

    SelectObject(mem, old);
    DeleteDC(mem);
    ReleaseDC(nullptr, screen);
}

static void HidePop(Pop *p) {
    KillTimer(p->hwnd, ID_TIMER_FRAME);
    KillTimer(p->hwnd, ID_TIMER_LIFE);
    KillTimer(p->hwnd, ID_TIMER_FADE);
    ShowWindow(p->hwnd, SW_HIDE);
    p->busy = false;
}

static void ShowPop(Pop *p, POINT at) {
    KillTimer(p->hwnd, ID_TIMER_FRAME);
    KillTimer(p->hwnd, ID_TIMER_LIFE);
    KillTimer(p->hwnd, ID_TIMER_FADE);

    p->busy    = true;
    p->frame   = 0;
    p->alpha   = 255;
    p->elapsed = 0;
    p->x = at.x - (int)g.gif.width / 2;
    p->y = at.y - (int)g.gif.height / 2;

    SetWindowPos(p->hwnd, HWND_TOPMOST, p->x, p->y,
                 (int)g.gif.width, (int)g.gif.height,
                 SWP_NOACTIVATE | SWP_SHOWWINDOW);
    PaintPop(p, 255);

    if (g.gif.frames.size() > 1)
        SetTimer(p->hwnd, ID_TIMER_FRAME, g.gif.frames[0].delay, nullptr);

    UINT solid = (g.showMs > kFadeMs) ? (g.showMs - kFadeMs) : 50;
    SetTimer(p->hwnd, ID_TIMER_LIFE, solid, nullptr);
}

static LRESULT CALLBACK PopProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp) {
    Pop *p = (Pop *)GetWindowLongPtrW(hwnd, GWLP_USERDATA);
    if (!p) return DefWindowProcW(hwnd, msg, wp, lp);

    if (msg == WM_TIMER) {
        switch (wp) {
            case ID_TIMER_FRAME:
                p->frame = (p->frame + 1) % (UINT)g.gif.frames.size();
                PaintPop(p, p->alpha);
                SetTimer(hwnd, ID_TIMER_FRAME, g.gif.frames[p->frame].delay, nullptr);
                return 0;

            case ID_TIMER_LIFE:
                KillTimer(hwnd, ID_TIMER_LIFE);
                SetTimer(hwnd, ID_TIMER_FADE, kFadeStepMs, nullptr);
                return 0;

            case ID_TIMER_FADE: {
                int step = (int)(255 * kFadeStepMs / (kFadeMs ? kFadeMs : 1));
                if (step < 1) step = 1;
                int next = (int)p->alpha - step;
                if (next <= 0) { HidePop(p); return 0; }
                p->alpha = (BYTE)next;
                PaintPop(p, p->alpha);
                return 0;
            }
            default: break;
        }
    }
    return DefWindowProcW(hwnd, msg, wp, lp);
}

static Pop *CreatePop() {
    Pop *p = new Pop();
    p->hwnd = CreateWindowExW(
        WS_EX_LAYERED | WS_EX_TRANSPARENT | WS_EX_TOPMOST |
            WS_EX_TOOLWINDOW | WS_EX_NOACTIVATE,
        kPopClass, L"", WS_POPUP,
        0, 0, (int)g.gif.width, (int)g.gif.height,
        nullptr, nullptr, g.inst, nullptr);
    if (!p->hwnd) { delete p; return nullptr; }
    SetWindowLongPtrW(p->hwnd, GWLP_USERDATA, (LONG_PTR)p);
    return p;
}

static void Fire(POINT at) {
    if (!g.enabled || g.pops.empty()) return;

    Pop *pop = nullptr;
    for (size_t i = 0; i < g.pops.size(); i++)
        if (!g.pops[i]->busy) { pop = g.pops[i]; break; }
    if (!pop) {                          // machine-gun clicker: recycle
        pop = g.pops[g.popCursor % (int)g.pops.size()];
        g.popCursor++;
    }

    ShowPop(pop, at);
    PlayBang(g.audio);
}

// -------------------------------------------------------------- mouse hook

// Low-level hooks are on a hard timeout -- do nothing here but hand the point
// to the message loop, or Windows quietly unhooks us.
static LRESULT CALLBACK MouseProc(int code, WPARAM wp, LPARAM lp) {
    if (code == HC_ACTION && g.enabled) {
        switch (wp) {
            case WM_LBUTTONDOWN:
            case WM_RBUTTONDOWN:
            case WM_MBUTTONDOWN:
            case WM_XBUTTONDOWN: {
                MSLLHOOKSTRUCT *m = (MSLLHOOKSTRUCT *)lp;
                PostMessageW(g.main, WM_ROCK_FIRE, (WPARAM)m->pt.x, (LPARAM)m->pt.y);
                break;
            }
            default: break;
        }
    }
    return CallNextHookEx(nullptr, code, wp, lp);   // click passes through
}

// ------------------------------------------------------ install / autostart

static std::wstring SelfPath() {
    wchar_t buf[MAX_PATH] = {};
    GetModuleFileNameW(nullptr, buf, MAX_PATH);
    return std::wstring(buf);
}

static std::wstring InstallDir() {
    wchar_t *local = nullptr;
    std::wstring dir;
    if (SUCCEEDED(SHGetKnownFolderPath(FOLDERID_LocalAppData, 0, nullptr, &local))) {
        dir = std::wstring(local) + L"\\TheRockWare";
        CoTaskMemFree(local);
    }
    return dir;
}

static bool StartupEnabled() {
    HKEY key;
    if (RegOpenKeyExW(HKEY_CURRENT_USER, kRunKey, 0, KEY_READ, &key) != ERROR_SUCCESS)
        return false;
    bool found = RegQueryValueExW(key, kRunValue, nullptr, nullptr, nullptr, nullptr)
                 == ERROR_SUCCESS;
    RegCloseKey(key);
    return found;
}

static void SetStartup(bool on, const std::wstring &exe) {
    HKEY key;
    if (RegCreateKeyExW(HKEY_CURRENT_USER, kRunKey, 0, nullptr, 0,
                        KEY_SET_VALUE, nullptr, &key, nullptr) != ERROR_SUCCESS)
        return;
    if (on) {
        std::wstring quoted = L"\"" + exe + L"\"";
        RegSetValueExW(key, kRunValue, 0, REG_SZ, (const BYTE *)quoted.c_str(),
                       (DWORD)((quoted.size() + 1) * sizeof(wchar_t)));
    } else {
        RegDeleteValueW(key, kRunValue);
    }
    RegCloseKey(key);
}

static int DoInstall() {
    std::wstring dir = InstallDir();
    if (dir.empty()) return 1;
    CreateDirectoryW(dir.c_str(), nullptr);
    std::wstring dest = dir + L"\\therockware.exe";

    // Close a running copy so the file isn't locked.
    HWND running = FindWindowW(kMainClass, nullptr);
    if (running) { PostMessageW(running, WM_CLOSE, 0, 0); Sleep(600); }

    if (!CopyFileW(SelfPath().c_str(), dest.c_str(), FALSE)) {
        MessageBoxW(nullptr, L"Could not copy the executable into %LOCALAPPDATA%.",
                    kAppName, MB_ICONERROR);
        return 1;
    }
    SetStartup(true, dest);
    ShellExecuteW(nullptr, L"open", dest.c_str(), nullptr, nullptr, SW_SHOWNORMAL);
    MessageBoxW(nullptr,
                L"Installed and running.\n\n"
                L"It starts with Windows and lives in the notification area "
                L"(the ^ tray) -- right-click the icon for Pause / Test Pop / Quit.",
                kAppName, MB_ICONINFORMATION);
    return 0;
}

static int DoUninstall() {
    SetStartup(false, L"");
    HWND running = FindWindowW(kMainClass, nullptr);
    if (running) { PostMessageW(running, WM_CLOSE, 0, 0); Sleep(600); }

    std::wstring dir = InstallDir();
    if (!dir.empty()) {
        std::wstring dest = dir + L"\\therockware.exe";
        if (!DeleteFileW(dest.c_str()) && GetLastError() == ERROR_ACCESS_DENIED) {
            // We are that file: have cmd delete it once we have exited.
            std::wstring cmd = L"/c timeout /t 2 /nobreak >nul & del /q \"" + dest +
                               L"\" & rmdir \"" + dir + L"\"";
            ShellExecuteW(nullptr, L"open", L"cmd.exe", cmd.c_str(), nullptr, SW_HIDE);
        } else {
            RemoveDirectoryW(dir.c_str());
        }
    }
    MessageBoxW(nullptr, L"Uninstalled.", kAppName, MB_ICONINFORMATION);
    return 0;
}

// ----------------------------------------------------------------- tray UI

static void UpdateTrayTip() {
    const wchar_t *state = g.enabled ? L"TheRockWare - armed"
                                     : L"TheRockWare - paused";
    wcscpy_s(g.nid.szTip, state);
    Shell_NotifyIconW(NIM_MODIFY, &g.nid);
}

static void ShowTrayMenu(HWND hwnd) {
    POINT pt;
    GetCursorPos(&pt);
    HMENU menu = CreatePopupMenu();
    AppendMenuW(menu, MF_STRING, IDM_TOGGLE, g.enabled ? L"Pause" : L"Resume");
    AppendMenuW(menu, MF_STRING, IDM_TEST, L"Test Pop");
    AppendMenuW(menu, MF_STRING | (StartupEnabled() ? MF_CHECKED : 0),
                IDM_STARTUP, L"Start with Windows");
    AppendMenuW(menu, MF_SEPARATOR, 0, nullptr);
    AppendMenuW(menu, MF_STRING, IDM_QUIT, L"Quit TheRockWare");

    SetForegroundWindow(hwnd);          // so the menu dismisses properly
    TrackPopupMenu(menu, TPM_RIGHTBUTTON | TPM_BOTTOMALIGN, pt.x, pt.y, 0, hwnd, nullptr);
    PostMessageW(hwnd, WM_NULL, 0, 0);
    DestroyMenu(menu);
}

static LRESULT CALLBACK MainProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp) {
    switch (msg) {
        case WM_ROCK_FIRE: {
            POINT pt = {(int)(LONG)wp, (int)(LONG)lp};
            Fire(pt);
            return 0;
        }

        case WM_ROCK_TRAY:
            if (LOWORD(lp) == WM_RBUTTONUP || LOWORD(lp) == WM_LBUTTONUP)
                ShowTrayMenu(hwnd);
            return 0;

        case WM_COMMAND:
            switch (LOWORD(wp)) {
                case IDM_TOGGLE:
                    g.enabled = !g.enabled;
                    if (!g.enabled)
                        for (size_t i = 0; i < g.pops.size(); i++) HidePop(g.pops[i]);
                    UpdateTrayTip();
                    return 0;
                case IDM_TEST: {
                    POINT pt; GetCursorPos(&pt);
                    bool was = g.enabled;
                    g.enabled = true;
                    Fire(pt);
                    g.enabled = was;
                    return 0;
                }
                case IDM_STARTUP: {
                    bool on = !StartupEnabled();
                    SetStartup(on, SelfPath());
                    return 0;
                }
                case IDM_QUIT:
                    DestroyWindow(hwnd);
                    return 0;
                default: break;
            }
            return 0;

        case WM_CLOSE:
            DestroyWindow(hwnd);
            return 0;

        case WM_DESTROY:
            Shell_NotifyIconW(NIM_DELETE, &g.nid);
            PostQuitMessage(0);
            return 0;

        default: break;
    }
    return DefWindowProcW(hwnd, msg, wp, lp);
}

// -------------------------------------------------------------- app entry

static UINT PrimaryDpi() {
    HMODULE user32 = GetModuleHandleW(L"user32.dll");
    if (user32) {
        typedef UINT(WINAPI * GetDpiForSystemFn)(void);
        GetDpiForSystemFn fn = (GetDpiForSystemFn)GetProcAddress(user32, "GetDpiForSystem");
        if (fn) return fn();
    }
    HDC dc = GetDC(nullptr);
    UINT dpi = dc ? (UINT)GetDeviceCaps(dc, LOGPIXELSX) : 96;
    if (dc) ReleaseDC(nullptr, dc);
    return dpi ? dpi : 96;
}

static void EnableDpiAwareness() {
    HMODULE user32 = GetModuleHandleW(L"user32.dll");
    if (!user32) return;
    typedef BOOL(WINAPI * SetCtxFn)(DPI_AWARENESS_CONTEXT);
    SetCtxFn fn = (SetCtxFn)GetProcAddress(user32, "SetProcessDpiAwarenessContext");
    if (fn) fn(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);
    else SetProcessDPIAware();
}

int WINAPI wWinMain(HINSTANCE inst, HINSTANCE, LPWSTR cmdLine, int) {
    if (wcsstr(cmdLine, L"--install"))   return DoInstall();
    if (wcsstr(cmdLine, L"--uninstall")) return DoUninstall();

    HANDLE mutex = CreateMutexW(nullptr, TRUE, kMutexName);
    if (mutex && GetLastError() == ERROR_ALREADY_EXISTS) return 0;   // already running

    EnableDpiAwareness();
    CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);
    MFStartup(MF_VERSION, MFSTARTUP_LITE);

    g.inst = inst;

    if (!DecodeGif(g.gif, PrimaryDpi())) {
        MessageBoxW(nullptr, L"The embedded gif failed to decode.", kAppName, MB_ICONERROR);
        return 1;
    }
    if (!InitAudio(g.audio))
        MessageBoxW(nullptr, L"Audio unavailable -- running silent.", kAppName, MB_ICONWARNING);

    // Stay on screen as long as the meme is audible, within sane bounds.
    UINT want = g.audio.durationMs > g.gif.totalMs ? g.audio.durationMs : g.gif.totalMs;
    g.showMs = (std::min)((std::max)(want, kMinShowMs), kMaxShowMs);

    WNDCLASSEXW wc = {};
    wc.cbSize        = sizeof(wc);
    wc.lpfnWndProc   = MainProc;
    wc.hInstance     = inst;
    wc.lpszClassName = kMainClass;
    RegisterClassExW(&wc);

    wc.lpfnWndProc   = PopProc;
    wc.lpszClassName = kPopClass;
    RegisterClassExW(&wc);

    // Not HWND_MESSAGE: a message-only window cannot take the foreground,
    // which leaves the tray menu stuck open. Ordinary window, never shown.
    g.main = CreateWindowExW(WS_EX_TOOLWINDOW, kMainClass, kAppName,
                             WS_OVERLAPPED, 0, 0, 0, 0,
                             nullptr, nullptr, inst, nullptr);
    if (!g.main) return 1;

    for (int i = 0; i < kPoolSize; i++) {
        Pop *p = CreatePop();
        if (p) g.pops.push_back(p);
    }

    g.nid.cbSize           = sizeof(g.nid);
    g.nid.hWnd             = g.main;
    g.nid.uID              = 1;
    g.nid.uFlags           = NIF_ICON | NIF_MESSAGE | NIF_TIP;
    g.nid.uCallbackMessage = WM_ROCK_TRAY;
    g.nid.hIcon            = LoadIconW(inst, MAKEINTRESOURCEW(1));
    if (!g.nid.hIcon) g.nid.hIcon = LoadIconW(nullptr, IDI_APPLICATION);
    wcscpy_s(g.nid.szTip, L"TheRockWare - armed");
    Shell_NotifyIconW(NIM_ADD, &g.nid);

    g.hook = SetWindowsHookExW(WH_MOUSE_LL, MouseProc, inst, 0);
    if (!g.hook)
        MessageBoxW(nullptr, L"Could not install the mouse hook.", kAppName, MB_ICONERROR);

    MSG msg;
    while (GetMessageW(&msg, nullptr, 0, 0) > 0) {
        TranslateMessage(&msg);
        DispatchMessageW(&msg);
    }

    if (g.hook) UnhookWindowsHookEx(g.hook);

    for (size_t i = 0; i < g.audio.voices.size(); i++) {
        g.audio.voices[i]->Stop(0);
        g.audio.voices[i]->DestroyVoice();
    }
    if (g.audio.master) g.audio.master->DestroyVoice();
    SafeRelease(&g.audio.engine);

    for (size_t i = 0; i < g.gif.frames.size(); i++) DeleteObject(g.gif.frames[i].bmp);
    for (size_t i = 0; i < g.pops.size(); i++) delete g.pops[i];

    MFShutdown();
    CoUninitialize();
    if (mutex) { ReleaseMutex(mutex); CloseHandle(mutex); }
    return 0;
}
